[package]
name = "pong"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version="1.7.3", features=["derive"] }
futures = "0.3.21"
rand = "0.8.5"
wgpu = "0.12.0"
winit = "0.26.1"